"""add waha message tracking

Revision ID: 6ad73239ccd4
Revises: c3f4bf42c94e
Create Date: 2026-05-08 09:10:14.540824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad73239ccd4'
down_revision: Union[str, None] = 'c3f4bf42c94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    with op.batch_alter_table('expenses') as batch_op:
        columns = [col['name'] for col in inspector.get_columns('expenses')]
        
        if 'credit_card_id' not in columns:
            batch_op.add_column(sa.Column('credit_card_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_exp_cc_id', 'credit_cards', ['credit_card_id'], ['id'])
            
        if 'invoice_date' not in columns:
            batch_op.add_column(sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True))
            
        if 'waha_message_id' not in columns:
            batch_op.add_column(sa.Column('waha_message_id', sa.String(), nullable=True))
            batch_op.create_index(batch_op.f('ix_expenses_waha_message_id'), ['waha_message_id'], unique=False)
            
        if 'bot_message_id' not in columns:
            batch_op.add_column(sa.Column('bot_message_id', sa.String(), nullable=True))
            batch_op.create_index(batch_op.f('ix_expenses_bot_message_id'), ['bot_message_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_waha_message_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_bot_message_id'), table_name='expenses')
    op.drop_column('expenses', 'bot_message_id')
    op.drop_column('expenses', 'waha_message_id')
    op.drop_column('expenses', 'invoice_date')
    op.drop_column('expenses', 'credit_card_id')
    # ### end Alembic commands ###
